{ pkgs }: let inherit (import ../../variables.nix) username; in pkgs.writeShellScriptBin "xsession" ''
	# Start Xorg via xsession file generated by home-manager.
	startx /home/${username}/.xsession
''
